openapi: 3.2.0
info:
  title: Digital BOP Loss History API
  description: Digital BOP API allows users to create and edit Businessowners Policy (BOP) quotes
  version: '1.0'
servers:
- url: https://gateway.amtrustgroup.com/digital-bop
- url: https://prod-apim-gw.amtrustservices.com/digital-bop
security:
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: Loss History
paths:
  /api/v1/quotes/{quoteId}/loss-history:
    post:
      tags:
      - Loss History
      summary: Add loss history
      operationId: post-api-v1-quotes-quoteid-loss-history
      parameters:
      - name: quoteId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/LossHistoryPostRequestDto'
            example:
              hasPriorCarrier: true
              hasZeroClaimsInLastThreeYears: false
              lossApplication: 2
          application/json:
            schema:
              $ref: '#/components/schemas/LossHistoryPostRequestDto'
            example:
              hasPriorCarrier: true
              hasZeroClaimsInLastThreeYears: false
              lossApplication: 2
          text/json:
            schema:
              $ref: '#/components/schemas/LossHistoryPostRequestDto'
            example:
              hasPriorCarrier: true
              hasZeroClaimsInLastThreeYears: false
              lossApplication: 2
          application/*+json:
            schema:
              $ref: '#/components/schemas/LossHistoryPostRequestDto'
            example:
              hasPriorCarrier: true
              hasZeroClaimsInLastThreeYears: false
              lossApplication: 2
      responses:
        '401':
          description: Bad or expired token. To resolve this error, generate a new or refreshed token.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorIApiResponse'
              example:
                responseId: f08be4f52bb2
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 401
                isOk: false
                errors:
                - httpStatusCode: 401
                  messageCode: ERR-NOTAUTHORIZED
                  title: Bearer token is not authorized
                  isOk: false
                maxErrorIndex: 0
                _v: AD
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorIApiResponse'
              example:
                responseId: f08be4f52bb2
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 401
                isOk: false
                errors:
                - httpStatusCode: 401
                  messageCode: ERR-NOTAUTHORIZED
                  title: Bearer token is not authorized
                  isOk: false
                maxErrorIndex: 0
                _v: AD
            text/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorIApiResponse'
              example:
                responseId: f08be4f52bb2
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 401
                isOk: false
                errors:
                - httpStatusCode: 401
                  messageCode: ERR-NOTAUTHORIZED
                  title: Bearer token is not authorized
                  isOk: false
                maxErrorIndex: 0
                _v: AD
        '403':
          description: The authenticated user or client does not have required permissions to complete this request.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ForbiddenErrorIApiResponse'
              example:
                responseId: a8b7b27ed202
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 403
                isOk: false
                errors:
                - httpStatusCode: 403
                  messageCode: ERR-FORBIDDEN
                  title: The token provided does not have permissions for the requested action
                  isOk: false
                maxErrorIndex: 0
                _v: AD
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenErrorIApiResponse'
              example:
                responseId: a8b7b27ed202
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 403
                isOk: false
                errors:
                - httpStatusCode: 403
                  messageCode: ERR-FORBIDDEN
                  title: The token provided does not have permissions for the requested action
                  isOk: false
                maxErrorIndex: 0
                _v: AD
            text/json:
              schema:
                $ref: '#/components/schemas/ForbiddenErrorIApiResponse'
              example:
                responseId: a8b7b27ed202
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 403
                isOk: false
                errors:
                - httpStatusCode: 403
                  messageCode: ERR-FORBIDDEN
                  title: The token provided does not have permissions for the requested action
                  isOk: false
                maxErrorIndex: 0
                _v: AD
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/LossHistoryPostResponseDtoIApiResponse'
              example:
                data:
                  hasPriorCarrier: true
                  hasZeroClaimsInLastThreeYears: false
                  lossApplication: Single Non-Weather Loss $5,000 - $10,000
                responseId: c7a705da7545
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 201
                isOk: true
                messages:
                - httpStatusCode: 200
                  messageCode: Deeplink
                  title: https://devk8s.amtrustgroup.com/usertest/webapp-nexus/AccountManagement/24786342
                  isOk: true
                maxMessageIndex: 0
                _v: AD
            application/json:
              schema:
                $ref: '#/components/schemas/LossHistoryPostResponseDtoIApiResponse'
              example:
                data:
                  hasPriorCarrier: true
                  hasZeroClaimsInLastThreeYears: false
                  lossApplication: Single Non-Weather Loss $5,000 - $10,000
                responseId: c7a705da7545
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 201
                isOk: true
                messages:
                - httpStatusCode: 200
                  messageCode: Deeplink
                  title: https://devk8s.amtrustgroup.com/usertest/webapp-nexus/AccountManagement/24786342
                  isOk: true
                maxMessageIndex: 0
                _v: AD
            text/json:
              schema:
                $ref: '#/components/schemas/LossHistoryPostResponseDtoIApiResponse'
              example:
                data:
                  hasPriorCarrier: true
                  hasZeroClaimsInLastThreeYears: false
                  lossApplication: Single Non-Weather Loss $5,000 - $10,000
                responseId: c7a705da7545
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 201
                isOk: true
                messages:
                - httpStatusCode: 200
                  messageCode: Deeplink
                  title: https://devk8s.amtrustgroup.com/usertest/webapp-nexus/AccountManagement/24786342
                  isOk: true
                maxMessageIndex: 0
                _v: AD
        '404':
          description: Not found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/NotFoundErrorIApiResponse'
              example:
                responseId: d4771723643b
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 404
                isOk: false
                errors:
                - httpStatusCode: 404
                  messageCode: ERR-ItemNotFound
                  title: Item was not found
                  isOk: false
                maxErrorIndex: 0
                _v: AD
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorIApiResponse'
              example:
                responseId: d4771723643b
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 404
                isOk: false
                errors:
                - httpStatusCode: 404
                  messageCode: ERR-ItemNotFound
                  title: Item was not found
                  isOk: false
                maxErrorIndex: 0
                _v: AD
            text/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorIApiResponse'
              example:
                responseId: d4771723643b
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 404
                isOk: false
                errors:
                - httpStatusCode: 404
                  messageCode: ERR-ItemNotFound
                  title: Item was not found
                  isOk: false
                maxErrorIndex: 0
                _v: AD
        '400':
          description: Validation error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequestErrorIApiResponse'
              example:
                responseId: 5d048eadde5b
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 400
                isOk: false
                errors:
                - httpStatusCode: 400
                  messageCode: ERR-ValidationErr
                  title: Validation Error
                  detail: Validation detail message
                  isOk: false
                maxErrorIndex: 0
                _v: AD
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorIApiResponse'
              example:
                responseId: 5d048eadde5b
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 400
                isOk: false
                errors:
                - httpStatusCode: 400
                  messageCode: ERR-ValidationErr
                  title: Validation Error
                  detail: Validation detail message
                  isOk: false
                maxErrorIndex: 0
                _v: AD
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorIApiResponse'
              example:
                responseId: 5d048eadde5b
                timeStamp: '2026-07-23T11:04:42.0000000+00:00'
                httpStatusCode: 400
                isOk: false
                errors:
                - httpStatusCode: 400
                  messageCode: ERR-ValidationErr
                  title: Validation Error
                  detail: Validation detail message
                  isOk: false
                maxErrorIndex: 0
                _v: AD
components:
  schemas:
    ApiPageRequest:
      type: object
      properties:
        skip:
          type: integer
          format: int32
        take:
          type: integer
          format: int32
        count:
          type: boolean
      additionalProperties: false
    UnauthorizedError:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messageType:
          enum:
          - 0 = Info
          - 1 = Error
          type: integer
          format: int32
        detail:
          type:
          - string
          - 'null'
        internal:
          type:
          - string
          - 'null'
        reference:
          type:
          - string
          - 'null'
        exception:
          $ref: '#/components/schemas/LogException'
        needsSanitization:
          type: boolean
          readOnly: true
        httpStatusCode:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
          readOnly: true
        messageCode:
          type:
          - string
          - 'null'
          readOnly: true
        title:
          type:
          - string
          - 'null'
          readOnly: true
        isOk:
          type: boolean
          readOnly: true
      additionalProperties: false
    ApiPaging:
      type: object
      properties:
        request:
          $ref: '#/components/schemas/ApiPageRequest'
        response:
          $ref: '#/components/schemas/ApiPageResponse'
      additionalProperties: false
    BadRequestErrorIApiResponse:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        timestamp:
          type: string
          format: date-time
        correlationID:
          type:
          - string
          - 'null'
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        paging:
          $ref: '#/components/schemas/ApiPaging'
        maxMsgIndex:
          type: integer
          format: int32
          readOnly: true
        maxErrIndex:
          type: integer
          format: int32
          readOnly: true
        isOk:
          type: boolean
        apiResponseVersion:
          type:
          - string
          - 'null'
          readOnly: true
        data:
          $ref: '#/components/schemas/BadRequestError'
      additionalProperties: false
    BadRequestError:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messageType:
          enum:
          - 0 = Info
          - 1 = Error
          type: integer
          format: int32
        internal:
          type:
          - string
          - 'null'
        reference:
          type:
          - string
          - 'null'
        exception:
          $ref: '#/components/schemas/LogException'
        needsSanitization:
          type: boolean
          readOnly: true
        httpStatusCode:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
          readOnly: true
        messageCode:
          type:
          - string
          - 'null'
          readOnly: true
        title:
          type:
          - string
          - 'null'
          readOnly: true
        detail:
          type:
          - string
          - 'null'
          readOnly: true
        isOk:
          type: boolean
          readOnly: true
      additionalProperties: false
    UnauthorizedErrorIApiResponse:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        timestamp:
          type: string
          format: date-time
        correlationID:
          type:
          - string
          - 'null'
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        paging:
          $ref: '#/components/schemas/ApiPaging'
        maxMsgIndex:
          type: integer
          format: int32
          readOnly: true
        maxErrIndex:
          type: integer
          format: int32
          readOnly: true
        isOk:
          type: boolean
        apiResponseVersion:
          type:
          - string
          - 'null'
          readOnly: true
        data:
          $ref: '#/components/schemas/UnauthorizedError'
      additionalProperties: false
    ApiPageResponse:
      type: object
      properties:
        first:
          type:
          - string
          - 'null'
        previous:
          type:
          - string
          - 'null'
        current:
          type:
          - string
          - 'null'
        next:
          type:
          - string
          - 'null'
        last:
          type:
          - string
          - 'null'
        pageSize:
          type:
          - integer
          - 'null'
          format: int32
        count:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: false
    LogException:
      type: object
      properties:
        exceptionId:
          type: string
          format: uuid
        module:
          type:
          - string
          - 'null'
        class:
          type:
          - string
          - 'null'
        targetSite:
          type:
          - string
          - 'null'
        httpWebEventCode:
          type:
          - integer
          - 'null'
          format: int32
        httpStatusValue:
          type:
          - integer
          - 'null'
          format: int32
        httpStatusCode:
          type:
          - string
          - 'null'
        httpHtmlMessage:
          type:
          - string
          - 'null'
        properties:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - string
            - 'null'
        innerException:
          $ref: '#/components/schemas/LogException'
        message:
          type:
          - string
          - 'null'
        source:
          type:
          - string
          - 'null'
        stackTrace:
          type:
          - string
          - 'null'
        helpLink:
          type:
          - string
          - 'null'
        method:
          type:
          - string
          - 'null'
        data:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - string
            - 'null'
        errorCode:
          type:
          - string
          - 'null'
        exceptionType:
          type:
          - string
          - 'null'
        baseException:
          $ref: '#/components/schemas/LogException'
      additionalProperties: false
    ForbiddenErrorIApiResponse:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        timestamp:
          type: string
          format: date-time
        correlationID:
          type:
          - string
          - 'null'
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        paging:
          $ref: '#/components/schemas/ApiPaging'
        maxMsgIndex:
          type: integer
          format: int32
          readOnly: true
        maxErrIndex:
          type: integer
          format: int32
          readOnly: true
        isOk:
          type: boolean
        apiResponseVersion:
          type:
          - string
          - 'null'
          readOnly: true
        data:
          $ref: '#/components/schemas/ForbiddenError'
      additionalProperties: false
    NotFoundErrorIApiResponse:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        timestamp:
          type: string
          format: date-time
        correlationID:
          type:
          - string
          - 'null'
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        paging:
          $ref: '#/components/schemas/ApiPaging'
        maxMsgIndex:
          type: integer
          format: int32
          readOnly: true
        maxErrIndex:
          type: integer
          format: int32
          readOnly: true
        isOk:
          type: boolean
        apiResponseVersion:
          type:
          - string
          - 'null'
          readOnly: true
        data:
          $ref: '#/components/schemas/NotFoundError'
      additionalProperties: false
    NotFoundError:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messageType:
          enum:
          - 0 = Info
          - 1 = Error
          type: integer
          format: int32
        detail:
          type:
          - string
          - 'null'
        internal:
          type:
          - string
          - 'null'
        reference:
          type:
          - string
          - 'null'
        exception:
          $ref: '#/components/schemas/LogException'
        needsSanitization:
          type: boolean
          readOnly: true
        httpStatusCode:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
          readOnly: true
        messageCode:
          type:
          - string
          - 'null'
          readOnly: true
        title:
          type:
          - string
          - 'null'
          readOnly: true
        isOk:
          type: boolean
          readOnly: true
      additionalProperties: false
    LossHistoryPostRequestDto:
      required:
      - hasPriorCarrier
      - lossApplication
      type: object
      properties:
        hasPriorCarrier:
          type: boolean
        hasZeroClaimsInLastThreeYears:
          type: boolean
        lossApplication:
          maximum: 6.0
          minimum: 0.0
          type: integer
          description: 1 - Single Loss < $5,000<br/>2 - Single Non - Weather Loss $5, 000 - $10, 000<br/>3 - Single Non - Weather Loss > $10, 000<br/>4 - Single Weather Loss $5, 000 - $25, 000<br/>5 - Single Weather Loss > 25, 000<br/>6 - Two or More Losses
          format: int32
      additionalProperties: false
    LossHistoryPostResponseDtoIApiResponse:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        timestamp:
          type: string
          format: date-time
        correlationID:
          type:
          - string
          - 'null'
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiMessage'
        paging:
          $ref: '#/components/schemas/ApiPaging'
        maxMsgIndex:
          type: integer
          format: int32
          readOnly: true
        maxErrIndex:
          type: integer
          format: int32
          readOnly: true
        isOk:
          type: boolean
        apiResponseVersion:
          type:
          - string
          - 'null'
          readOnly: true
        data:
          $ref: '#/components/schemas/LossHistoryPostResponseDto'
      additionalProperties: false
    LossHistoryPostResponseDto:
      type: object
      properties:
        hasPriorCarrier:
          type: boolean
        hasZeroClaimsInLastThreeYears:
          type: boolean
        lossApplication:
          type:
          - string
          - 'null'
      additionalProperties: false
    ApiMessage:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messageCode:
          type:
          - string
          - 'null'
        messageType:
          enum:
          - 0 = Info
          - 1 = Error
          type: integer
          format: int32
        title:
          type:
          - string
          - 'null'
        detail:
          type:
          - string
          - 'null'
        internal:
          type:
          - string
          - 'null'
        reference:
          type:
          - string
          - 'null'
        exception:
          $ref: '#/components/schemas/LogException'
        isOk:
          type: boolean
        needsSanitization:
          type: boolean
          readOnly: true
      additionalProperties: false
    ForbiddenError:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        httpStatus:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
        messageType:
          enum:
          - 0 = Info
          - 1 = Error
          type: integer
          format: int32
        detail:
          type:
          - string
          - 'null'
        internal:
          type:
          - string
          - 'null'
        reference:
          type:
          - string
          - 'null'
        exception:
          $ref: '#/components/schemas/LogException'
        needsSanitization:
          type: boolean
          readOnly: true
        httpStatusCode:
          enum:
          - 100 = Continue
          - 101 = SwitchingProtocols
          - 102 = Processing
          - 103 = EarlyHints
          - 200 = OK
          - 201 = Created
          - 202 = Accepted
          - 203 = NonAuthoritativeInformation
          - 204 = NoContent
          - 205 = ResetContent
          - 206 = PartialContent
          - 207 = MultiStatus
          - 208 = AlreadyReported
          - 226 = IMUsed
          - 300 = MultipleChoices
          - 300 = Ambiguous
          - 301 = MovedPermanently
          - 301 = Moved
          - 302 = Found
          - 302 = Redirect
          - 303 = SeeOther
          - 303 = RedirectMethod
          - 304 = NotModified
          - 305 = UseProxy
          - 306 = Unused
          - 307 = TemporaryRedirect
          - 307 = RedirectKeepVerb
          - 308 = PermanentRedirect
          - 400 = BadRequest
          - 401 = Unauthorized
          - 402 = PaymentRequired
          - 403 = Forbidden
          - 404 = NotFound
          - 405 = MethodNotAllowed
          - 406 = NotAcceptable
          - 407 = ProxyAuthenticationRequired
          - 408 = RequestTimeout
          - 409 = Conflict
          - 410 = Gone
          - 411 = LengthRequired
          - 412 = PreconditionFailed
          - 413 = RequestEntityTooLarge
          - 414 = RequestUriTooLong
          - 415 = UnsupportedMediaType
          - 416 = RequestedRangeNotSatisfiable
          - 417 = ExpectationFailed
          - 421 = MisdirectedRequest
          - 422 = UnprocessableEntity
          - 422 = UnprocessableContent
          - 423 = Locked
          - 424 = FailedDependency
          - 426 = UpgradeRequired
          - 428 = PreconditionRequired
          - 429 = TooManyRequests
          - 431 = RequestHeaderFieldsTooLarge
          - 451 = UnavailableForLegalReasons
          - 500 = InternalServerError
          - 501 = NotImplemented
          - 502 = BadGateway
          - 503 = ServiceUnavailable
          - 504 = GatewayTimeout
          - 505 = HttpVersionNotSupported
          - 506 = VariantAlsoNegotiates
          - 507 = InsufficientStorage
          - 508 = LoopDetected
          - 510 = NotExtended
          - 511 = NetworkAuthenticationRequired
          type: integer
          format: int32
          readOnly: true
        messageCode:
          type:
          - string
          - 'null'
          readOnly: true
        title:
          type:
          - string
          - 'null'
          readOnly: true
        isOk:
          type: boolean
          readOnly: true
      additionalProperties: false
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: subscriber_id
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
